
/*
 * Copyright © 2015-2017, AnHui Mobiao technology co. LTD Inc. All Rights Reserved.
 */

package com.jtech.toa.user.oa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "OAWS", targetNamespace = "http://oaws.absen.com/", wsdlLocation = "http://192.168.100.102:8080/AbsenWS/webServices/oaWS?wsdl")
@WebServiceClient(name = "OAWS", targetNamespace = "http://oaws.absen.com/", wsdlLocation = "http://service.absen.cn:9092/AbsenWS/webServices/oaWS?wsdl")
public class OAWS_Service
    extends Service
{

    private final static URL OAWS_WSDL_LOCATION;
    private final static WebServiceException OAWS_EXCEPTION;
    private final static QName OAWS_QNAME = new QName("http://oaws.absen.com/", "OAWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("http://192.168.100.102:8080/AbsenWS/webServices/oaWS?wsdl");
            url = new URL("http://service.absen.cn:9092/AbsenWS/webServices/oaWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OAWS_WSDL_LOCATION = url;
        OAWS_EXCEPTION = e;
    }

    public OAWS_Service() {
        super(__getWsdlLocation(), OAWS_QNAME);
    }

    public OAWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OAWS_QNAME, features);
    }

    public OAWS_Service(URL wsdlLocation) {
        super(wsdlLocation, OAWS_QNAME);
    }

    public OAWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OAWS_QNAME, features);
    }

    public OAWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OAWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OAWS
     */
    @WebEndpoint(name = "OAWSPort")
    public OAWS getOAWSPort() {
        return super.getPort(new QName("http://oaws.absen.com/", "OAWSPort"), OAWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OAWS
     */
    @WebEndpoint(name = "OAWSPort")
    public OAWS getOAWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://oaws.absen.com/", "OAWSPort"), OAWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OAWS_EXCEPTION!= null) {
            throw OAWS_EXCEPTION;
        }
        return OAWS_WSDL_LOCATION;
    }

}
